name: build for release

on:
  release:
    types: [published]

jobs:
  build-mod:
    name: Build Mod
    runs-on: ubuntu-latest
    env:
      MODKIT_VERSION: 0.11.1.12-beta-release-866
      ECO_BRANCH: staging
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Fetch dependencies
      run: dotnet restore ./EcoSmartTaxMod/EcoSmartTaxMod.csproj
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Build
      run: dotnet build ./EcoSmartTaxMod/EcoSmartTaxMod.csproj --configuration Release --no-restore /p:AssemblyVersion=${{github.event.release.tag_name}}
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-binaries-${{github.event.release.tag_name}}
        path: EcoSmartTaxMod/bin/Release/net8.0/EcoSmartTaxMod.*
  deploy:
    name: Upload Release Assets
    needs:
    - build-mod
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact (mod)
        id: download-mod
        uses: actions/download-artifact@v4
        with:
          name: mod-binaries-${{github.event.release.tag_name}}
      - name: Upload release asset (mod)
        id: upload-release-asset-mod
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-mod.outputs.download-path}}/EcoSmartTaxMod.dll
          asset_name: EcoSmartTaxMod.dll
          asset_content_type: application/octet-stream
