name: build for staging

on:
  push:
    branches:
      - 'staging'

jobs:
  build-mod:    
    name: Build Mod
    runs-on: ubuntu-latest
    env:
      MODKIT_VERSION: 0.11.1.12-beta-release-866
      ECO_BRANCH: staging
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Fetch dependencies
      run: dotnet restore ./EcoSmartTaxMod/EcoSmartTaxMod.csproj
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Build
      run: dotnet build ./EcoSmartTaxMod/EcoSmartTaxMod.csproj --configuration Release --no-restore
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-binaries-staging
        path: EcoSmartTaxMod/bin/Release/net8.0/EcoSmartTaxMod.*
